---
title: "Example_Word"
author: "Boyi Guo"
date: "6/26/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r example}

devtools::install_github('boyiguo1/KableOne')

library(labelled)
library(tidyverse)
library(magrittr)
library(survival)
library(kableExtra)
library(KableOne)
library(flextable)
library(officer)


source("R/to_word.R")


data = pbc %>%
  dplyr::select(
    age, sex, status, trt, stage, ascites, bili, edema, albumin
  ) %>%
  dplyr::mutate(
    status=factor(
      status, levels = c(0:2),
      labels = c("Censored", "Transplant", "Dead")
    ),
    stage = factor(
      stage, levels = c(1:4),
      labels = c("One", "Two", "Three", "Four")
    ),
    trt=factor(
      trt, levels=c(1:2),
      labels = c("Drug A", "Drug B")
    ),
    ascites=factor(
      ascites, levels=c(0:1),
      labels = c("No", "Yes")
    ),
    sex = fct_recode(
      sex,
      'Male'='m',
      'Female'='f'
    ),
    edema = factor(
      edema,
      levels=c(0, 0.5, 1),
      labels=c("None", "A little", "Lots")
    )
  ) 

```
```{r}

data = data %>%
  set_variable_labels(
    status = "Status at last contact",
    trt = "Treatment group",
    age = 'Age, years',
    sex = 'Sex at birth',
    ascites = 'Ascites',
    bili = 'Bilirubin levels, mg/dl',
    edema = 'Is there Edema?'
  ) %>%
  set_variable_groups(
    Outcomes = c('status'),
    Exposures = c('ascites','bili','edema','trt','albumin','stage')
  ) 
```

```{r}

tbl_one = data %>%
  tibble_one(
    formula = ~ . | trt,
    include.allcats = FALSE,
    include.freq = FALSE,
    include.pval = TRUE
  )

```

```{r}

# TODO(boyiguo1): Fix the bug that when use_groups, all the first column are bolded, should relate to the use of bold function
  
  
tmp <- tbl_one %>% 
  to_word_test(
    use_groups = FALSE,
    apply_format_steps = T
    )

tmp 
```

